@@include("../../blocks/components/tabs-block/tabs-block.js")
@@include("../../blocks/components/multi-menu/multi-menu.js")
@@include("../../blocks/components/form/form.js")
@@include("../../blocks/components/field-file/field-file.js")
@@include("../../blocks/components/select/select.js")
@@include("../../blocks/components/spoiler/spoiler.js")
@@include("../../blocks/components/s-filter/s-filter.js")

document.addEventListener('DOMContentLoaded', () => {
    tabsBlockInit()
    multiMenu()
    fileFieldInit()
    validation()
    selects()
    spoilers()
    sFilter()
})