@@include("../../blocks/modules/header/header.js")
@@include("../../blocks/modules/main-burger/main-burger.js")
@@include("../../blocks/modules/info-slider/info-slider.js")
@@include("../../blocks/modules/auto-slider/auto-slider.js")
@@include("../../blocks/modules/home-info/home-info.js")
@@include("../../blocks/modules/home-process/home-process.js")
@@include("../../blocks/modules/sidebar-layout/sidebar-layout.js")
@@include("../../blocks/modules/m-table/m-table.js")
@@include("../../blocks/modules/modals/modals.js")
@@include("../../blocks/modules/s-vacancy/s-vacancy.js")
@@include("../../blocks/modules/s-partners/s-partners.js")
@@include("../../blocks/modules/programm-info/programm-info.js")

document.addEventListener('DOMContentLoaded', () => {
    headerHeight()
    headerMenu()
    sidebarLayout()
    mTable()
    mainBurger()
    modalsInit()
    sVacancySliders()
    sPartners()
    homeInfo()
    homeProcess()
    infoSlider()
    autoSliders()
    programmInfo()
})