name: Deploy selected folders to FTP

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare deploy directory
        run: |
          mkdir deploy
          cp -r dist/img deploy/
          cp -r dist/styles deploy/
          cp -r dist/js deploy/
          cp -r dist/fonts deploy/

      - name: FTP Deploy selected folders only
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
          local-dir: ./deploy
